import type { NextPage } from 'next';
import Head from 'next/head';
import Shmurgle from '../components/Shmurgle';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Shmurgle</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Shmurgle />
            </main>
        </div>
    );
};

export default Home;
